'use client';
import { useState } from "react";
import WizardHeader from "../components/WizardHeader";

const Assesment = () => {
  const score = localStorage.getItem("score");
  const scoreObj = JSON.parse(score as any);
  const [state, setState] = useState(scoreObj.score || null || undefined);

  return (
    <WizardHeader
      p="This Score is generated by AI. So it might be well suited for you or not. Please take it with a grain of salt."
      h2="Get Your Score"
    >
      <div className="align-center flex h-full w-full justify-between gap-4">
        {scoreObj && (
          <div className="align-start flex flex-col justify-start gap-4">
            <div className="flex flex-col items-center my-5">
              <h1 className="text-lg font-medium ">
                Your chance to secure this job:
              </h1>
              
              <p className="text-md ">{scoreObj.score} out of 5</p>
            </div>

            <div className="flex flex-col justify-start gap-2">
              <h1 className="text-lg font-medium">
                Improvements for Securing the Job:
              </h1>
              <div className="text-md ">
                <ul className="flex flex-col gap-4">
                  {scoreObj.improvements.map((improvement: any, index: number) => (
                    <li className="list-disc" key={index}>
                      {improvement}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
            <div className="flex flex-col justify-start gap-2">
              <h1 className="text-lg font-medium">
                Explanation about your Assesment:
              </h1>
              <p className="text-md">{scoreObj.explanation}</p>
            </div>
          </div>
        )}
      </div>
    </WizardHeader>
  );
};

export default Assesment
